# Generated by Django 2.2.1 on 2019-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
