# Generated by Django 2.2.1 on 2019-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contract_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='amount',
        ),
    ]
