# Generated by Django 2.2.1 on 2019-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contract_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='value',
            new_name='actual_value',
        ),
        migrations.AddField(
            model_name='contract',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
