# Generated by Django 2.2.1 on 2019-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190606_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
