# Generated by Django 2.1.4 on 2019-05-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_payment_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contract',
        ),
    ]
