# Generated by Django 2.1.4 on 2019-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190531_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contract',
        ),
    ]
