# Generated by Django 2.2.1 on 2019-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
